[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_DISABLE_ESLINT = "1"
  NEXT_IGNORE_TYPE_ERROR = "1"
  TYPESCRIPT_SKIP_TYPECHECKING = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 